// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc9kF34E31epvQyTNppEK-FlX_mSt0cDo',
    appId: '1:330558914048:android:e98ea2997f74c438f162e5',
    messagingSenderId: '330558914048',
    projectId: 'courseflutter-aa72b',
    storageBucket: 'courseflutter-aa72b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADmGz7hBsAKG5jxSqEN-syqYW_Tcj_nQw',
    appId: '1:330558914048:ios:5fae159e87dfb9a1f162e5',
    messagingSenderId: '330558914048',
    projectId: 'courseflutter-aa72b',
    storageBucket: 'courseflutter-aa72b.appspot.com',
    androidClientId: '330558914048-0lf765pqekjkrp152ppm4cr8t9108ghe.apps.googleusercontent.com',
    iosClientId: '330558914048-iqs0kluu5cvhgcf90k3a789dkmiqfjpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseflutter',
  );

}